basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views, urls

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}))

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = ''
        self.fields['email'].label = ''
        self.fields['password'].label = ''

    class Meta():
        model = User
        fields = ('username','email','password')

        widgets = {
            'username': forms.TextInput(attrs = {'class':'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs = {'class':'form-control', 'placeholder': 'Email address'}),
        }


class UserProfileInfoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserProfileInfoForm, self).__init__(*args, **kwargs)
        self.fields['portfolio_site'].label = ''

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

        widgets = {
            'portfolio_site': forms.TextInput(attrs = {'class':'form-control', 'placeholder': 'Portfolio site'}),
        }

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
from django.contrib import messages

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                                            {'user_form':user_form,
                                            'profile_form':profile_form,
                                            'registered':registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            messages.warning(request, 'Invalid username or password.')
            return render(request, 'basic_app/login.html')
            print("Someone tried to login and failed!")
            print("Username: {} and Password {}".format(username, password))
    else:
        return render(request, 'basic_app/login.html', {})

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">SILVERCYBER</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" href="{% url 'basic_app:register' %}">Register <span class="sr-only">(current)</span></a>

          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <!-- <nav class = 'navbar navbar-expand-lg navbar-light bg-light'>
      <div class="container">
        <ul class= 'nav navbar-nav'>
          <li><a class='navbar-brand' href="{% url 'index' %}">SILVERCYBER</a></li>
          <li><a class='nav-link' href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class='nav-link' href="{% url 'basic_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav> -->

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<style media="screen">
  body {
    background-image: url("{% static "/images/scene.jpg" %}");
    background-size: cover;
  }
  .container {
    text-align: center;
  }
</style>

<div class="container">
  <br><br>
  <h1>Hello There!!!</h1>
</div>

{% endblock %}

templates/basic_app/login.html
<!DOCTYPE html>
<html lang="" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <style media="screen">
      body {
        background: skyblue;
      }
      .login-card {
        background-color:white;
        width:40%;
        height:400px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        margin:auto;
        border-radius:4px;
        margin-top:100px;
      }
      .login-content {
        text-align: center;
      }
      #login-head {
        padding-top:50px;
      }
      .messages {
        color: red;
      }

      @media screen and (max-width:600px) {
        .login-card {
          width:90%;
        }

    </style>
  </head>
  <body>
    <div class="container">
      <div class="container login-card" style="">
        <div class="container login-content">
          <h2 id="login-head">Login</h2><br>
          {% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
          {% endif %}

          <form action="{% url 'basic_app:user_login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" id="exampleInputUsername1" name="username" aria-describedby="userHelp" placeholder="Username">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
            </div>

            <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button><br>
          </form>

          <div class="">
            <p>Don't have an account? <a href="{% url 'basic_app:register' %}">Register here</a></p>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

templates/basic_app/registration.html
<!DOCTYPE html>
<html lang="" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <style media="screen">
      body {
        background: skyblue;
      }
      .register-card {
        background-color:white;
        width:40%;
        height:580px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        margin:auto;
        border-radius:4px;
        margin-top:50px;
      }
      .register-content {
        text-align: center;
      }
      #register-head {
        padding-top:50px;
      }

      @media screen and (max-width:600px) {
        .register-card {
          width:90%;
        }
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="container register-card" style="">
        <div class="container register-content">
          {% if registered %}
            <h2 id="register-head">Thank you for registering!</h2>
          {% else %}
            <h2 id="register-head">Register here!</h2>
            <br>
            <form action="{% url 'basic_app:register' %}" method="post">
              {% csrf_token %}
              {{ user_form.as_p}}
              {{ profile_form.as_p }}

              <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button><br>
            </form>

          {% endif %}

          <div class="">
            <p>Already have an account? <a href="{% url 'basic_app:user_login' %}">Login here</a></p>
          </div>

        </div>
      </div>
    </div>

  </body>
</html>



<!-- <div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
    <h1>Register here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p}}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>

    {% endif %}
</div> -->